name: Docker Build and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up DockerHub credentials
      run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV

    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t my-docker-image .

    - name: Validate Docker Image
      run: docker run --rm my-docker-image sh -c "your_validation_command"

    - name: Tag Docker Image
      run: docker tag my-docker-image ${{ secrets.DOCKER_REGISTRY }}/my-docker-image:latest

    - name: Push Docker Image to Registry
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/my-docker-image:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: docker-context
        path: .
    - name: Set up Azure Blob Storage credentials
      run: echo "AZURE_STORAGE_ACCOUNT=${{ secrets.AZURE_STORAGE_ACCOUNT }}" >> $GITHUB_ENV
      
    - name: Upload to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob upload --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name ${{ secrets.AZURE_STORAGE_CONTAINER }} \
            --type block \
            --name my-docker-image.tar \
            --type block \
            --content-type application/x-tar \
            --type block \
            --type block \
            --type block

