name: Validate and Copy to Blob Storage

on:
  push:
    branches:
      - main
      
env:
  ZIP_FILE_NAME: file.zip
  EXTRACT_FOLDER_NAME: Folder
  STORAGE_ACCOUNT_NAME: reusestacc01
  CONTAINER_NAME: rscontainer
  

jobs:
  validate_and_copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Archive
        id: extraction
        run: |
          ls -al
          unzip $ZIP_FILE_NAME -d $EXTRACT_FOLDER_NAME
          ls -al

      - name: Validate Archive/Docker Image
        id: validation
        run: |
          # use md5 checksum for validation

          # Assuming the validation output is stored in a variable called VALIDATION_RESULT
          VALIDATION_RESULT="Validation successful"

          echo "::set-output name=validation_result::$VALIDATION_RESULT"      

      - name: Copy to Blob Storage
        id: copy_blob
        run: |

          az login --service-principal -u "f0d22f1c-d2f2-4870-aba1-83f0f86495ab" -p "odU8Q~l5SqnWdcCTW2S_qCS5kt-5StE-iWfEzc3o" --tenant "2f64943b-5ec5-41e9-9829-934b5391ef50" 

          az storage blob upload --account-key BhhJKhV7FCxRudThA9oFtiv+UpvQs7XG6bzKrZR6rZyfNf0I3ja2wqNnqEovyilvu4Oc1SKHK2pK+AStKb0Rdw== --account-name $STORAGE_ACCOUNT_NAME --container-name CONTAINER_NAME --name test/new1.txt --file test/new1.txt

          COPY_RESULT="Content copied to blob storage"

          echo "::set-output name=copy_result::$COPY_RESULT"
 
      - name: Validate Blob Storage Content
        id: validation_blob
        run: |
          # Validate the content in blob storage matches the expanded content
          # Example: Compare content in blob storage with expanded content

          VALIDATION_BLOB_RESULT="Validation of blob storage content successful"

          echo "::set-output name=validation_blob_result::$VALIDATION_BLOB_RESULT"

      - name: Log Validation Results
        run: |
          echo "Validation Result: ${{ steps.validation.outputs.validation_result }}"
          echo "Copy to Blob Storage Result: ${{ steps.copy_blob.outputs.copy_result }}"
          echo "Blob Storage Validation Result: ${{ steps.validation_blob.outputs.validation_blob_result }}"
          